Fix extraConfigmaps support
This was broken by #2666. Inside the `range` loop, `.` refers to the current configmap item, not the root context. This causes an error when installing:
```sh
$ helm install -n renovate renovate renovate/renovate -f values.yaml
Error: INSTALLATION FAILED: template: renovate/templates/extra-configmap.yaml:7:16: executing "renovate/templates/extra-configmap.yaml" at <include "renovate.namespace" .>: error calling include: template: renovate/templates/_helpers.tpl:14:20: executing "renovate.namespace" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```